// AI Service — Unified AI communication layer
import { storage } from '../utils/storage.js';
import { providers, getProvider, getModelInfo } from './providers.js';
import { prompts } from './prompts.js';

export class AIService {
  constructor() {
    this.currentProvider = storage.get('ai-provider', 'openai');
    this.currentModel = storage.get('ai-model', 'gpt-4o');
    this.apiKeys = storage.get('api-keys', {});
    this.conversationHistory = [];
  }

  setProvider(providerId) {
    this.currentProvider = providerId;
    const provider = getProvider(providerId);
    if (provider) this.currentModel = provider.defaultModel;
    storage.set('ai-provider', providerId);
    storage.set('ai-model', this.currentModel);
  }

  setModel(modelId) {
    this.currentModel = modelId;
    storage.set('ai-model', modelId);
  }

  setApiKey(providerId, key) {
    this.apiKeys[providerId] = key;
    storage.set('api-keys', this.apiKeys);
  }

  getApiKey(providerId) {
    return this.apiKeys[providerId] || '';
  }

  clearHistory() {
    this.conversationHistory = [];
  }

  async sendMessage(userMessage, context = null) {
    const prompt = prompts.chat(userMessage, context);
    return this._makeRequest(prompt.system, prompt.user);
  }

  async generateCode(description, language, context) {
    const prompt = prompts.generate(description, language, context);
    return this._makeRequest(prompt.system, prompt.user);
  }

  async explainCode(code, language) {
    const prompt = prompts.explain(code, language);
    return this._makeRequest(prompt.system, prompt.user);
  }

  async refactorCode(code, language, instructions) {
    const prompt = prompts.refactor(code, language, instructions);
    return this._makeRequest(prompt.system, prompt.user);
  }

  async debugCode(code, language, error) {
    const prompt = prompts.debug(code, language, error);
    return this._makeRequest(prompt.system, prompt.user);
  }

  async writeTests(code, language) {
    const prompt = prompts.test(code, language);
    return this._makeRequest(prompt.system, prompt.user);
  }

  async reviewCode(code, language) {
    const prompt = prompts.review(code, language);
    return this._makeRequest(prompt.system, prompt.user);
  }

  async _makeRequest(systemPrompt, userMessage) {
    this.conversationHistory.push({ role: 'user', content: userMessage });
    const provider = getProvider(this.currentProvider);
    if (!provider) {
      return this._simulateResponse(userMessage);
    }

    const apiKey = this.apiKeys[this.currentProvider];
    if (provider.requiresKey && !apiKey) {
      return this._simulateResponse(userMessage);
    }

    try {
      const response = await this._callAPI(provider, systemPrompt, apiKey);
      const assistantMessage = response;
      this.conversationHistory.push({ role: 'assistant', content: assistantMessage });
      return assistantMessage;
    } catch (error) {
      console.warn('API call failed, using simulated response:', error);
      return this._simulateResponse(userMessage);
    }
  }

  async _callAPI(provider, systemPrompt, apiKey) {
    const messages = [
      { role: 'system', content: systemPrompt },
      ...this.conversationHistory
    ];

    const headers = { 'Content-Type': 'application/json' };

    if (provider.id === 'anthropic') {
      headers['x-api-key'] = apiKey;
      headers['anthropic-version'] = '2023-06-01';
    } else if (provider.id === 'local') {
      // No auth for local
    } else {
      headers['Authorization'] = `Bearer ${apiKey}`;
    }

    const body = provider.id === 'anthropic'
      ? { model: this.currentModel, max_tokens: 4096, system: systemPrompt, messages: this.conversationHistory }
      : provider.id === 'local'
        ? { model: this.currentModel, messages, stream: false }
        : { model: this.currentModel, messages, max_tokens: 4096 };

    const res = await fetch(provider.apiEndpoint, {
      method: 'POST', headers, body: JSON.stringify(body)
    });

    if (!res.ok) throw new Error(`API error: ${res.status}`);
    const data = await res.json();

    if (provider.id === 'anthropic') return data.content[0].text;
    if (provider.id === 'local') return data.message.content;
    return data.choices[0].message.content;
  }

  _simulateResponse(userMessage) {
    const lower = userMessage.toLowerCase();
    let response;

    if (lower.includes('generate') || lower.includes('create') || lower.includes('build') || lower.includes('make')) {
      response = `Here's the generated code based on your request:\n\n\`\`\`javascript\n// Generated by Vibe AI\nclass Component {\n  constructor(props) {\n    this.props = props;\n    this.state = {};\n  }\n\n  render() {\n    return \`<div class="component">\n      <h2>\${this.props.title || 'Component'}</h2>\n      <p>\${this.props.description || 'A dynamic component'}</p>\n    </div>\`;\n  }\n\n  mount(selector) {\n    document.querySelector(selector).innerHTML = this.render();\n  }\n}\n\nexport default Component;\n\`\`\`\n\n💡 **Tips:**\n- Customize the \`render()\` method for your needs\n- Add event listeners in the \`mount()\` method\n- Use the state object for reactive data`;
    } else if (lower.includes('explain')) {
      response = `## Code Explanation\n\nLet me break down this code for you:\n\n1. **Structure**: The code follows a modular pattern with clear separation of concerns\n2. **Key Functions**: Each function has a single responsibility\n3. **Data Flow**: Data flows from top to bottom through function calls\n4. **Best Practices**: Uses modern ES6+ syntax with proper error handling\n\n> 💡 **Pro Tip:** Consider adding TypeScript for better type safety and IDE support.`;
    } else if (lower.includes('debug') || lower.includes('fix') || lower.includes('error')) {
      response = `## 🐛 Bug Analysis\n\nI found the following issues:\n\n### Issue 1: Potential null reference\n\`\`\`diff\n- const value = data.items.length;\n+ const value = data?.items?.length ?? 0;\n\`\`\`\n\n### Issue 2: Missing error handling\n\`\`\`javascript\ntry {\n  const result = await fetchData();\n  // Process result\n} catch (error) {\n  console.error('Failed to fetch:', error);\n  // Handle gracefully\n}\n\`\`\`\n\n✅ Apply these fixes and your code should work correctly!`;
    } else if (lower.includes('refactor')) {
      response = `## ♻️ Refactored Code\n\nHere's the improved version:\n\n\`\`\`javascript\n// Refactored: Cleaner, more maintainable approach\nconst processData = (items) =>\n  items\n    .filter(item => item.active)\n    .map(({ id, name, value }) => ({\n      id,\n      label: name.trim(),\n      amount: parseFloat(value)\n    }))\n    .sort((a, b) => b.amount - a.amount);\n\`\`\`\n\n**Changes made:**\n- ✅ Replaced loop with functional chain\n- ✅ Added destructuring for clarity\n- ✅ Improved variable naming\n- ✅ Added sorting for better UX`;
    } else if (lower.includes('test')) {
      response = `## 🧪 Unit Tests\n\n\`\`\`javascript\nimport { describe, it, expect } from 'vitest';\nimport { processData } from './module';\n\ndescribe('processData', () => {\n  it('should filter active items', () => {\n    const input = [\n      { active: true, name: 'A', value: 10 },\n      { active: false, name: 'B', value: 20 },\n    ];\n    expect(processData(input)).toHaveLength(1);\n  });\n\n  it('should handle empty array', () => {\n    expect(processData([])).toEqual([]);\n  });\n\n  it('should sort by value descending', () => {\n    const input = [\n      { active: true, name: 'A', value: 10 },\n      { active: true, name: 'B', value: 30 },\n    ];\n    const result = processData(input);\n    expect(result[0].amount).toBeGreaterThan(result[1].amount);\n  });\n});\n\`\`\`\n\n✅ Tests cover: filtering, empty input, and sorting logic.`;
    } else {
      response = `I'd be happy to help! Here are some things I can do:\n\n- ✨ **Generate Code** — Tell me what to build\n- 💡 **Explain Code** — Paste code and I'll break it down\n- 🔄 **Refactor** — I'll improve your code quality\n- 🐛 **Debug** — Share errors and I'll find the fix\n- 🧪 **Write Tests** — I'll create comprehensive tests\n- 📝 **Code Review** — Get professional feedback\n\nJust describe what you need, or use the agent action buttons below! 🚀\n\n> **Tip:** Connect your API key in Settings (Ctrl+,) to use real AI models like GPT-4o, Claude, or Gemini.`;
    }

    this.conversationHistory.push({ role: 'assistant', content: response });
    return new Promise(resolve => {
      setTimeout(() => resolve(response), 300 + Math.random() * 700);
    });
  }
}
